server:
  port: 8081
healthchecks:
  - title: Test Check
    url: http://localhost:8080/v2/actuator/health
    job_frequency: 10min
    alert_frequency: 1h
    checks:
      - type: status
        value: 200
      - type: json
        path: details.JCoConnection.details.AMB_SERVER.state
        value: ALIVE
      - type: json
        path: details.kafkaTopicConnection.details.customer-env.state
        value: active
